### ISSUE TITLE
Please make the link to maps embed an image of the maps to preview a lot easier

### ISSUE THREAD

**Issue by lololy100** [shannonturner/metro-map-maker#25]
This would be a really good feature as me and other people share maps on apps like discord regularly and it would be very convenient if it could show an images of the map we are sharing with the link.

**Comment by shannonturner** [comment]
This was added in v6 (https://github.com/shannonturner/metro-map-maker/releases/tag/v6.0), thanks so much for the suggestion! See https://www.youtube.com/watch?v=OErGHMzAekw for more details
