### ISSUE TITLE
Improvement: Right Menu Design & UI Library Recommendation

### ISSUE THREAD

**Issue by ramazansancar** [shannonturner/metro-map-maker#65]
By making improvements to the right menu design. I think a softer look with rounded, material design colors might be nice.

I think popular UI libraries such as React.js and Vue.js would be good for the project to receive development support from more users.

I'm open to feedback. Thanks for this project.

**Comment by shannonturner** [comment]
Thanks for the suggestions, but I'm not sure what I'd use react or vue for in this project -- I'm able to do pretty much everything I want to without them, and would prefer not to add unnecessary dependencies.

Glad to hear you like the project, and happy mapmaking!
